pipeline:
  compile:
    image: openjdk:10-jdk
    commands:
      - ./gradlew installDist

  publish:
    image: plugins/docker
    repo: registry.fritz.box:5000/preacher
    registry: registry.fritz.box:5000
    insecure: true
    auto_tag: true
    tags: latest
    when:
      branch: master

  slack:
    image: plugins/slack
    channel: bot
    secrets: [ slack_webhook ]
    image_url: https://cdn.marketeer.space/drone-icon.png
    username: Drone
    when:
      status: [ success, failure ]